### ISSUE TITLE
You should incorporate Git-flow into your production workflow

### ISSUE THREAD

**Issue by BLOODTIDE12** [getnamo/hydra-ue4#3]
Hi there,
I would suggest incorporating Git-flow into your production workflow over your current trunk (committing to solely 1 branch) method, as to keep backwards compatibility with older versions of Unreal Engine 4.

Here is a diagram of Git-flow in action:
![alt text](http://nvie.com/img/2009/12/Screen-shot-2009-12-24-at-11.32.03.png "git-flow branching model")

You can find [more information here](http://nvie.com/posts/a-successful-git-branching-model/)

**Comment by getnamo** [comment]
For now the current structure is maintained for simplicity, if/when github release and push work as a single command, I'll revisit the issue.
