### ISSUE TITLE
Impossible to package 4.10 game using the plugin

### ISSUE THREAD

**Issue by LaP0573** [getnamo/hydra-ue4#5]
Hello,

I have a project currently using the Hydra plugin in UE4.10, and after packaging it and trying to launch the game, I get this :

        MachineId:595E01B1444ED99F3D293181649D4B6D
	EpicAccountId:

	Access violation - code c0000005 (first/second chance not available)

	""

	TestMotionSickness_Win64_Shipping!FHydraPlugin::DataDelegate() [f:\data\projects\ue4\testmotionsickness - copie\plugins\hydraplugin\source\hydraplugin\private\fhydraplugin.cpp:855]
	TestMotionSickness_Win64_Shipping!UHydraPluginComponent::InitializeComponent() [f:\data\projects\ue4\testmotionsickness - copie\plugins\hydraplugin\source\hydraplugin\private\hydracomponent.cpp:21]
	TestMotionSickness_Win64_Shipping!AActor::InitializeComponents()
	TestMotionSickness_Win64_Shipping!AActor::PostActorConstruction()
	TestMotionSickness_Win64_Shipping!AActor::FinishSpawning()
	TestMotionSickness_Win64_Shipping!AActor::PostSpawnInitialize()
	TestMotionSickness_Win64_Shipping!UWorld::SpawnActor()
	TestMotionSickness_Win64_Shipping!UWorld::SpawnActor()
	TestMotionSickness_Win64_Shipping!AGameMode::SpawnDefaultPawnFor_Implementation()
	TestMotionSickness_Win64_Shipping!AGameMode::execSpawnDefaultPawnFor()
	TestMotionSickness_Win64_Shipping!UFunction::Invoke()
	TestMotionSickness_Win64_Shipping!UObject::ProcessEvent()
	TestMotionSickness_Win64_Shipping!AActor::ProcessEvent()
	TestMotionSickness_Win64_Shipping!AGameMode::SpawnDefaultPawnFor()
	TestMotionSickness_Win64_Shipping!AGameMode::RestartPlayer()
	TestMotionSickness_Win64_Shipping!AGameMode::HandleMatchHasStarted()
	TestMotionSickness_Win64_Shipping!AGameMode::SetMatchState()
	TestMotionSickness_Win64_Shipping!UWorld::BeginPlay()
	TestMotionSickness_Win64_Shipping!UEngine::LoadMap()
	TestMotionSickness_Win64_Shipping!UEngine::Browse()
	TestMotionSickness_Win64_Shipping!UGameInstance::StartGameInstance()
	TestMotionSickness_Win64_Shipping!UGameEngine::Init()
	TestMotionSickness_Win64_Shipping!FEngineLoop::Init()
	TestMotionSickness_Win64_Shipping!GuardedMain()
	TestMotionSickness_Win64_Shipping!GuardedMainWrapper()
	TestMotionSickness_Win64_Shipping!WinMain()
	TestMotionSickness_Win64_Shipping!__scrt_common_main_seh() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:264]
	kernel32
	ntdll

Any idea what might be causing it ? I've pasted the plugins folder next to my binaries folder in the packaged project. Note that I get the exact same issue when trying to launch the game via the editor with "Standalone game".

**Comment by getnamo** [comment]
It looks like it's a load order problem, controller reference hasn't been set in line 855 by the time it's called. Will have a look into it this weekend to see if I can't find a solution.

**Comment by LaP0573** [comment]
Alright thank you, could it be related to the fact that the computer I'm currently trying to launch the game on has no hydra plugged in ?

**Comment by getnamo** [comment]
Presence of hydra should make no difference, the plugin supports hot-plugging and will correctly initialize in either case.

Interesting note on the standalone, it seems the presence of the editor makes the hydra loaded early whereas if it only has the game, it loads too late.

**Comment by LaP0573** [comment]
Yup I can confirm for the hydra, I made a quick test yesterday evening when I had a hydra at hand and it still crashed. Same for standalone game.

Do you have any control over load order, from the plugin's perspective ? Or are you just just at UE4's mercy ?

**Comment by getnamo** [comment]
You can have control by choosing how to handle your code loading things, but I'm still not sure of a solution.

**Comment by getnamo** [comment]
Give the latest fixes by Jonathan a try and let me know if that fixed things for you or if something is still missing.

**Comment by LaP0573** [comment]
Sorry for the delay, couldn't give it a try. I just packaged the game and it's, indeed, working fine in packaged form (and starting the game in a new window works in the editor now). Perfect :)
