### ISSUE TITLE
UE4 - 11 Preview 5 Error in compiling HydraPlugin

### ISSUE THREAD

**Issue by dschaberg** [getnamo/hydra-ue4#9]
May or may not be an issue with the official 4.11 release. Heads up!

Error    C2259    'FHydraController': cannot instantiate abstract class    
X:\Unreal Projects\Preview5\Plugins\HydraPlugin\Source\HydraPlugin\Private\FHydraPlugin.cpp    852    

virtual TSharedPtr< class IInputDevice > CreateInputDevice(const TSharedRef< FGenericApplicationMessageHandler >& InMessageHandler) override
    {
        controllerReference = new FHydraController(InMessageHandler);

**Comment by getnamo** [comment]
Experimental branch has a fix for this: https://github.com/getnamo/hydra-ue4/tree/experimental

It should work for 4.11 proper as well, if you want it early grab it from there.

**Comment by dschaberg** [comment]
Awesome. You dont sleep. Saw your link for VR editor hydra plugin as well.
Badass!
